# Generated by Django 5.2.8 on 2026-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0007_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
